Pixel 3 XL:
  first_charge_mv_roi:
  - 223
  - 2363
  - 383
  - 443
  msgs_roi:
  - 230
  - 996
  - 986
  - 100
  my_pokeballs_roi:
  - 43
  - 426
  - 223
  - 63
  my_roi:
  - 40
  - 373
  - 530
  - 50
  my_typing_roi:
  - 16
  - 280
  - 163
  - 73
  opp_pokeballs_roi:
  - 1174
  - 426
  - 223
  - 63
  opp_roi:
  - 870
  - 373
  - 530
  - 50
  opp_typing_roi:
  - 1256
  - 275
  - 163
  - 73
  second_charge_mv_roi:
  - 834
  - 2363
  - 383
  - 443
Pixel 7 Pro:
  first_charge_mv_roi:
  - 183
  - 1968
  - 243
  - 243
  msgs_roi:
  - 173
  - 677
  - 720
  - 100
  my_pokeballs_roi:
  - 20
  - 183
  - 186
  - 70
  my_roi:
  - 13
  - 143
  - 440
  - 46
  my_typing_roi:
  - 10
  - 76
  - 123
  - 70
  opp_pokeballs_roi:
  - 874
  - 183
  - 186
  - 70
  opp_roi:
  - 627
  - 143
  - 440
  - 46
  opp_typing_roi:
  - 942
  - 71
  - 123
  - 70
  second_charge_mv_roi:
  - 654
  - 1968
  - 243
  - 243
