Pixel 3 XL:
  first_charge_mv_roi:
  - 223
  - 2363
  - 383
  - 443
  msgs_roi:
  - 230
  - 996
  - 986
  - 100
  my_pokeballs_roi:
  - 43
  - 426
  - 223
  - 63
  my_roi:
  - 40
  - 373
  - 530
  - 50
  my_typing_roi:
  - 16
  - 280
  - 163
  - 73
  opp_pokeballs_roi:
  - 1174
  - 426
  - 223
  - 63
  opp_roi:
  - 870
  - 373
  - 530
  - 50
  opp_typing_roi:
  - 1256
  - 275
  - 163
  - 73
  second_charge_mv_roi:
  - 834
  - 2363
  - 383
  - 443
Pixel 7 Pro:
  first_charge_mv_roi:
  - 163
  - 1945
  - 286
  - 283
  msgs_roi:
  - 180
  - 680
  - 710
  - 100
  my_pokeballs_roi:
  - 20
  - 190
  - 183
  - 60
  my_roi:
  - 20
  - 146
  - 426
  - 46
  my_typing_roi:
  - 10
  - 73
  - 120
  - 70
  opp_pokeballs_roi:
  - 877
  - 190
  - 183
  - 60
  opp_roi:
  - 634
  - 146
  - 426
  - 46
  opp_typing_roi:
  - 945
  - 68
  - 120
  - 70
  second_charge_mv_roi:
  - 631
  - 1945
  - 286
  - 283
