Pixel 3 XL:
  first_charge_mv_roi:
  - 223
  - 2363
  - 383
  - 443
  msgs_roi:
  - 230
  - 996
  - 986
  - 100
  my_pokeballs_roi:
  - 43
  - 426
  - 223
  - 63
  my_roi:
  - 40
  - 373
  - 530
  - 50
  my_typing_roi:
  - 16
  - 280
  - 163
  - 73
  opp_pokeballs_roi:
  - 1174
  - 426
  - 223
  - 63
  opp_roi:
  - 870
  - 373
  - 530
  - 50
  opp_typing_roi:
  - 1256
  - 275
  - 163
  - 73
  second_charge_mv_roi:
  - 834
  - 2363
  - 383
  - 443
Pixel 7 Pro:
  first_charge_mv_roi:
    coords:
    - 306
    - 2089
    - 123
    object_type: circ
  msgs_roi:
    coords:
    - 176
    - 687
    - 713
    - 93
    object_type: rect
  my_pokeballs_roi:
    coords:
    - 23
    - 190
    - 183
    - 70
    object_type: rect
  my_roi:
    coords:
    - 16
    - 143
    - 416
    - 46
    object_type: rect
  my_typing_roi:
    coords:
    - 20
    - 76
    - 120
    - 70
    object_type: rect
  opp_pokeballs_roi:
    coords:
    - 874
    - 190
    - 183
    - 70
    object_type: rect
  opp_roi:
    coords:
    - 648
    - 143
    - 416
    - 46
    object_type: rect
  opp_typing_roi:
    coords:
    - 935
    - 71
    - 120
    - 70
    object_type: rect
  second_charge_mv_roi:
    coords:
    - 774
    - 2089
    - 123
    object_type: circ
